import { name, version } from "../../package.json"

interface RouteNode {
  segment: string
  fullPath: string
  children: Map<string, RouteNode>
  layout?: string
  page?: string
}

const isPrivate = (path: string) => {
  return path.split("/").some((seg) => seg.startsWith("_") && seg !== "_layout")
}

const indent = (code: string, tab = "  ") => {
  return code
    .split("\n")
    .map((line) => (line ? tab + line : line))
    .join("\n")
}

const toRoutePath = (segment: string) => {
  if (segment.startsWith("[...") && segment.endsWith("]")) return "$"
  if (segment.startsWith("[") && segment.endsWith("]"))
    return "$" + segment.slice(1, -1)
  return segment
}

const buildTree = (files: string[]) => {
  // index.tsx or page.tsx -> route("/", "index.tsx" or "page.tsx")
  // nested/index.tsx or nested/page.tsx -> route("/nested", "nested/index.tsx" or "nested/page.tsx")
  // [slug]/index.tsx or [slug]/page.tsx -> route("/$slug", "[slug]/index.tsx" or "[slug]/page.tsx")
  // (folder)/index.tsx or (folder)/page.tsx -> route("/", "(folder)/index.tsx" or "(folder)/page.tsx")
  // (folder)/nested/index.tsx or (folder)/nested/page.tsx -> route("/nested", "(folder)/nested/index.tsx" or "(folder)/nested/page.tsx")
  // (folder)/[slug]/index.tsx or (folder)/[slug]/page.tsx -> route("/$slug", "(folder)/[slug]/index.tsx" or "(folder)/[slug]/page.tsx")

  const root: RouteNode = { segment: "", fullPath: "", children: new Map() }

  for (const file of files) {
    if (isPrivate(file)) continue

    const parts = file.split("/")
    let currentNode = root

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i]
      const isLast = i === parts.length - 1
      const isFile = isLast && (part.endsWith(".tsx") || part.endsWith(".ts"))

      if (isFile) {
        if (part === "layout.tsx" || part === "__root.tsx") {
          currentNode.layout = file
        } else if (part === "page.tsx" || part === "index.tsx") {
          currentNode.page = file
        }
        continue
      }

      // Directory or file acting as directory
      if (!currentNode.children.has(part)) {
        currentNode.children.set(part, {
          segment: part,
          fullPath: parts.slice(0, i + 1).join("/"),
          children: new Map(),
        })
      }
      currentNode = currentNode.children.get(part)!
    }
  }

  return root
}

const processNode = (node: RouteNode): string[] => {
  const childrenCodes: string[] = []

  for (const child of node.children.values()) {
    childrenCodes.push(...processNode(child))
  }

  if (node.page) {
    if (node.segment.startsWith("[[...") && node.segment.endsWith("]]")) {
      childrenCodes.push(`route("$", "${node.page}")`)
      childrenCodes.push(`index("${node.page}")`)
    } else {
      childrenCodes.push(`index("${node.page}")`)
    }
  }

  const isRoot = node.segment === ""
  const isGroup = node.segment.startsWith("(") && node.segment.endsWith(")")
  const isOptionalCatchAll =
    node.segment.startsWith("[[...") && node.segment.endsWith("]]")

  const childrenString = childrenCodes.join(",\n")
  const indentedChildren = indent(childrenString)

  if (isRoot) {
    if (node.layout) {
      return [`rootRoute("${node.layout}", [\n${indentedChildren}\n])`]
    }
    return childrenCodes
  }

  if (isGroup || isOptionalCatchAll) {
    if (node.layout) {
      return [`layout("${node.layout}", [\n${indentedChildren}\n])`]
    }
    return childrenCodes
  }

  const routePath = toRoutePath(node.segment)

  if (node.layout) {
    return [
      `route("${routePath}", "${node.layout}", [\n${indentedChildren}\n])`,
    ]
  }

  if (childrenCodes.length > 0) {
    return [`route("${routePath}", [\n${indentedChildren}\n])`]
  }

  return []
}

export const template = (config: string[]) => {
  const root = buildTree(config)
  const result = processNode(root)
  const transformed =
    result.length === 1 ? result[0] : `[\n${indent(result.join(",\n"))}\n]`

  return `// @ts-nocheck

// This file was automatically generated by ${name}@${version}
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// prettier-ignore
import { index, layout, rootRoute, route } from "@tanstack/virtual-file-routes";

// prettier-ignore
export const routes = ${transformed};
`
}
