// @ts-nocheck

// This file was automatically generated by virtual-next-routes@0.0.8
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// prettier-ignore
import { index, layout, physical, rootRoute, route } from "@tanstack/virtual-file-routes";

// prettier-ignore
export const routes = rootRoute("layout.tsx", [
  route("/", "page.tsx"),
  route("/nested", "nested/page.tsx"),
  route("/nested/$slug", "nested/[slug]/page.tsx"),
  route("/nested/nested", "(folder)/nested/nested/page.tsx"),
  route("/nested/nested/$slug", "(folder)/nested/nested/[slug]/page.tsx")
]);
