// This file is auto-generated by virtual-next-routes v0.0.5. Do not edit directly.
        
import {
  index,
  layout,
  physical,
  rootRoute,
  route,
} from "@tanstack/virtual-file-routes"

export const routes = rootRoute('layout.tsx', [route('/dashboard', 'dashboard/page.tsx)'), route('/$id/yolo', '[id]/yolo/page.tsx)')])
