// @ts-nocheck

// This file was automatically generated by virtual-next-routes@0.0.17
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// prettier-ignore
import { index, layout, rootRoute, route } from "@tanstack/virtual-file-routes";

// prettier-ignore
export const routes = rootRoute("layout.tsx", [
  route("$slug", [
    route("nested", [
      index("[slug]/nested/page.tsx")
    ]),
    index("[slug]/page.tsx")
  ]),
  route("auth", "auth/layout.tsx", [

  ]),
  route("dashboard", "dashboard/layout.tsx", [
    route("analytics", [
      index("dashboard/analytics/page.tsx")
    ]),
    index("dashboard/page.tsx")
  ]),
  route("features", [
    layout("features/(settings)/layout.tsx", [
      route("account", [
        index("features/(settings)/account/page.tsx")
      ]),
      route("profile", [
        index("features/(settings)/profile/page.tsx")
      ])
    ]),
    index("features/page.tsx")
  ]),
  route("nested", [
    route("$slug", [
      index("nested/[slug]/page.tsx")
    ]),
    index("nested/page.tsx")
  ]),
  route("$group-slug", [
    index("(group)/[group-slug]/page.tsx")
  ]),
  route("group-page-one", [
    index("(group)/group-page-one/page.tsx")
  ]),
  route("group-page-two", [
    index("(group)/group-page-two/page.tsx")
  ]),
  route("$slug-a", [
    route("$slug-b", [
      index("[slug-a]/[slug-b]/page.tsx")
    ])
  ]),
  route("blog", [
    route("$slug", "blog/[slug]/layout.tsx", [
      index("blog/[slug]/page.tsx")
    ])
  ]),
  index("page.tsx")
]);
