import { name, version } from "../../package.json"

const pagesTransform = (config: string[]) => {
  // page.tsx -> route("/", "page.tsx")
  // nested/page.tsx -> route("/nested", "nested/page.tsx")
  // [slug]/page.tsx -> route("/$slug", "[slug]/page.tsx")
  // nested/[slug]/page.tsx -> route("/nested/$slug", "nested/[slug]/page.tsx")
  // nested/[slug]/nested/page.tsx -> route("/nested/$slug/nested", "nested/[slug]/nested/page.tsx")

  config = config.filter(
    (path) => path === "page.tsx" || path.endsWith("/page.tsx"),
  )

  return config
    .map((path) => {
      // Remove trailing '/page.tsx'
      const routeSegments = path
        .replace(/\/?page\.tsx$/, "")
        .split("/")
        .filter(Boolean)
      // Replace [slug] with $slug for route path
      const routePath =
        "/" +
        routeSegments
          .map((seg) =>
            seg.startsWith("[") && seg.endsWith("]")
              ? `$${seg.slice(1, -1)}`
              : seg,
          )
          .join("/")
      return `  route("${routePath === "/" ? "/" : routePath}", "${path}")`
    })
    .join(",\n")
}

export const template = (config: string[]) => {
  const transformed = config.includes("layout.tsx")
    ? `rootRoute("layout.tsx", [\n${pagesTransform(config)}\n])`
    : null

  return `// @ts-nocheck

// This file was automatically generated by ${name}@${version}
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.  

// prettier-ignore
import { index, layout, physical, rootRoute, route } from "@tanstack/virtual-file-routes";

// prettier-ignore
export const routes = ${transformed};
`
}
